---
- name: Exchange Keys between servers
  gather_facts: no
  become: yes
  become_user: "{{ BECOME_USER }}""
  hosts: all
  tasks:
    - name: SSH KeyGen command
      connection: local
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
      ignore_errors:yes
      run_once: true
    
    - name: read id_rsa.pub
      connection: local
      command: "cat ~/.ssh/id_rsa.pub"
      register: id_pub
      run_once: true
    
    - name: remote lineinfile for authorized_keys
      lineinfile:
        dest: /root/.ssh/authorized_keys
        line: "{{ id_pub_stdout }}"