---
- name: Exchange Keys between servers
  become: yes
  become_user: {{BECOME_USER}}
  hosts: all
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
    - name: Fetch the keyfile
      tags: run
      fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: ".ssh/{{TARGET_HOST}}-id_rsa.pub"
        flat: yes
    - name: Copy the key add to authorized_keys
      tags: run
      authorized_key:
        user: {{BECOME_USER}}
        state: present
        key: "{{ lookup('file','.ssh/{{TARGET_HOST}}-id_rsa.pub')}}"
      # when: "{{ TARGET_HOST != TARGET_HOST }}"
      # with_items: 
      #   - { dest: "{{groups['app'][1]}}"}
      #   - { dest: "{{groups['app'][0]}}"}
