---

- name: Install Base Packages
  include_tasks: centos7.yaml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Ubuntu 22.04 
  include_tasks: ubuntu2204.yaml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "22.04"