---
- name: Update and upgrade apt packages
  become_user: "{{ ubuntu_user }}"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install Base Packages
  become: true
  apt:
    name: "{{ package }}"
    state: latest
  loop: "{{ base_packages }}"
  loop_control:
    loop_var: package